# ---- general arguments ----
projectdir: /home/ubuntu/joanna/CWUNET/
savedir: /home/ubuntu/Data_guestxr/RESULTS-reverb-match-cond-u-net/
device: cpu
fs: 48000 

# ---- data and model parameters ----
sig_len: 98304 
rev_emb_len: 512 # length of the reverberation embedding
n_blocks_revenc: 12 # number of blocks in the Reverb Encoder
n_blocks_enc: 12 # number of blocks in the Encoder and Decoder of the Wave-U-Net
learnable_pooling: False # whether to use learnable pooling in the Reverb Encoder

# ---- dataset parameters ----
style_rir: null # null means it will be randomly selected (otherwise put the path to the style RIR)
content_rir: null # null means it will be randomly selected (otherwise put the path to the content RIR)
df_metadata: /home/ubuntu/joanna/CWUNET/dataset-metadata/ds2_metadata_example.csv
has_clones: False # whether the dataset has clones (i.e. for each RIR, it has an alternative RIR from the same room but different pos.)
p_noise: 0 # probability of adding noise in the training set
split: train

# ---- training parameters ----
modeltype: c_wunet 
num_epochs: 300
checkpoint_step: 10
batch_size: 8
learn_rate: 0.0001
trainscheme: "separate"
optimizer: adam
losstype: stft
loss_alphas: [[1]] 
store_outputs: 1

# arguments to resume training
resume_checkpoint: null
resume_tboard: null

# evaluation arguments
device: cuda
batch_size_eval: 2
checkpoint_development: 0
eval_file_name: eval_all.csv
eval_dir: 
eval_split: test
rt60diffmin: -3
rt60diffmax: 3
N_datapoints: 1000
train_results_file: /home/ubuntu/guestxr2/home/ubuntu/Data/RESULTS-reverb-match-cond-u-net/runs-exp-15-01-2024/18-01-2024--00-56_many-to-many_stft/checkpoint_best.pt
eval_tag: 
evalsavedir: 
